apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 5
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: archsoup/passin:43795ae
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:admin@postgres:5432/passin"
          # value: "postgresql://${DO_PG_USER}:${DO_PG_PASSWORD}@nlw-unite-cluster-do-user-16235693-0.c.db.ondigitalocean.com:25060/nlw-unite?sslmode=require"
        - name: API_BASE_URL
          value: "http://localhost:3333"
        ports:
        - containerPort: 3333
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 512Mi